name: audioplayer
description: A flutter plugin to play audio files
version: 0.4.0
author: Erick Ghaumez <erick@rxla.bz>
homepage: https://github.com/rxlabz/audioplayer

flutter:
  plugin:
    androidPackage: bz.rxla.audioplayer
    pluginClass: AudioplayerPlugin

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
